image: archlinux
packages:
  - meson
  - wayland
  - scdoc
sources:
  - https://github.com/djpohly/minshi
tasks:
  - setup: |
      cd minshi
      meson build -Dauto_features=enabled
  - build: |
      cd minshi
      ninja -C build
